//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class price
    {
        public System.DateTime date { get; set; }
        public long product_id { get; set; }
        public int price1 { get; set; }
        public System.Guid company_id { get; set; }
    
        public virtual company company { get; set; }
        public virtual product product { get; set; }
    }
}
