//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public System.Guid id { get; set; }
        public string login { get; set; }
        public string passwordhash { get; set; }
        public System.Guid salt { get; set; }
        public int role_id { get; set; }
        public long card_id { get; set; }
    
        public virtual discount_card discount_card { get; set; }
        public virtual role role { get; set; }
    }
}
